# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_custom_theme', '0002_auto_20181219_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='primary_button_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_hyperlink_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_search_icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_title_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='datasets_icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='datasets_icon_hover_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='datasets_title_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='jumbotron_hyperlink_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='navbar_search_icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_button_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_button_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_hyperlink_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_icon_hover_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_icon_title_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_sub_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_title_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
