# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_custom_theme', '0003_auto_20181219_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_hyperlink_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Big search hyperlink text'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Big search placeholder'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='big_search_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Big search title'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='datasets_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Datasets title'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='jumbotron_button_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='jumbotron_button_hide',
            field=models.BooleanField(default=False, verbose_name=b'Hide call to action'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='jumbotron_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Call to action link'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='jumbotron_button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Call to action text'),
        ),
        migrations.AddField(
            model_name='advancedgeonodethemecustomization',
            name='showcase_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Showcase title'),
        ),
        migrations.AlterField(
            model_name='advancedgeonodethemecustomization',
            name='body_bg',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y/%m', verbose_name=b'Body background'),
        ),
    ]
